kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
  # disableDefaultCNI: true
nodes:
# the control plane node config
- role: control-plane
  image:  kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    listenAddress: "0.0.0.0"
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    listenAddress: "0.0.0.0"
    hostPort: 443
    protocol: TCP
# one workers
- role: worker
  image:  kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
